services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: mydb
      MYSQL_USER: sa
      MYSQL_PASSWORD: <password>
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
