services:
  windows:
    image: docker.io/dockurr/windows
    container_name: xp-vm
    environment:
      VERSION: "xp"
      DISK_SIZE: "20G"
      RAM_SIZE: "3G"
      CPU_CORES: "2"
      USERNAME: ""
      PASSWORD: ""
    volumes:
      - /home/BahayFiles:/data
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3390/tcp
      - 3390:3390/udp
    stop_grace_period: 2m